# Copyright (c) 2024, NVIDIA CORPORATION.

{% set data = load_file_data("pyproject.toml") %}
{% set version = load_file_regex(
    load_file="numba_cuda/VERSION",
    regex_pattern="(?P<value>.*)"
)[0] %}
{% set project_data = data["project"] %}
{% set project_urls = project_data["urls"] %}

package:
  name: numba-cuda
  version: {{ version }}

source:
  path: ../../..

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numba >=0.59.1

about:
  home: {{ project_urls["Homepage"] }}
  dev_url: {{ project_urls["Repository"] }}
  doc_url: {{ project_urls["Documentation"] }}
  license: {{ project_data["license"]["text"] }}
  license_family: BSD
  license_file: LICENSE
  license_url: {{ project_urls["License"] }}
  summary: Numba CUDA target
