# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause
Name: Numba Bfloat16
Version: 0.0.2
GPU Arch:
    - sm_80 # sm_80 is the first CUDA architecture that supports bfloat16
Entry Point: ./numba_cuda/numba/cuda/include/13/cuda_bf16.h
File List:
    - ./numba_cuda/numba/cuda/include/13/cuda_bf16.h
Exclude: {}
Types:
    __nv_bfloat16_raw: Number
    __nv_bfloat16: Number
    __nv_bfloat162_raw: Type
    __nv_bfloat162: Type
    nv_bfloat16: Number
    nv_bfloat162: Type
Data Models:
    __nv_bfloat16_raw: PrimitiveModel
    __nv_bfloat16: PrimitiveModel
    nv_bfloat16: PrimitiveModel
    __nv_bfloat162_raw: StructModel
    __nv_bfloat162: StructModel
    nv_bfloat162: StructModel
Shim Include Override: "\"cuda_bf16.h\""
Use Separate Registry: True
