# Copyright (c) 2024, NVIDIA CORPORATION.

{% set data = load_file_data("pyproject.toml") %}
{% set version = load_file_regex(
    load_file="numba_cuda/VERSION",
    regex_pattern="(?P<value>.*)"
)[0] %}
{% set project_data = data.get("project") %}
{% set project_urls = project_data["urls"] %}

package:
  name: numba_cuda
  version: {{ version }}

source:
  path: ../../..

build:
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.26.4
    - ninja
    - sysroot_{{ target_platform }} 2.17
  host:
    - python
    - pip
    - scikit-build-core
  run:
    - python
    - numba >=0.60.0
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x.x') }}

about:
  home: {{ project_urls["Homepage"] }}
  dev_url: {{ project_urls["Repository"] }}
  doc_url: {{ project_urls["Documentation"] }}
  license: {{ project_data["license"]["text"] }}
  license_family: Apache
  license_file: LICENSE
  license_url: {{ project_urls["License"] }}
  summary: nvJitLink Python binding
