# Copyright (c) 2024, NVIDIA CORPORATION.
name: build

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: true

jobs:
  compute-matrix:
    runs-on: ubuntu-latest
    outputs:
      BUILD_MATRIX: ${{ steps.compute-matrix.outputs.BUILD_MATRIX }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute Build Matrix
        id: compute-matrix
        uses: ./.github/actions/compute-matrix
  build-wheels:
    needs:
      - compute-matrix
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.04
    with:
      build_type: branch
      script: "ci/build_wheel.sh"
      matrix_filter: ${{ needs.compute-matrix.outputs.BUILD_MATRIX }}
  build-conda:
    needs:
      - compute-matrix
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-build.yaml@branch-24.04
    with:
      build_type: branch
      script: "ci/build_conda.sh"
      matrix_filter: ${{ needs.compute-matrix.outputs.BUILD_MATRIX }}
  publish-wheels:
    needs:
      - build-wheels
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-publish.yaml@branch-24.04
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      sha: ${{ inputs.sha }}
      date: ${{ inputs.date }}
      package-name: numba_cuda
  publish-conda:
    needs:
     - build-conda
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-upload-packages.yaml@branch-24.04
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
